/**
 * CodeRegion — multi-region read/write layer over a Strudel document.
 *
 * The document is the single source of truth and belongs to the user. Panels
 * are guests: each owns one *region* (a span identified by a semantic anchor),
 * never the whole document. This service lets a panel author express a domain
 * rule without navigating raw ESTree nodes, and edit the document by pure string
 * splicing so the preamble and neighbouring regions stay intact, character for
 * character.
 *
 * Guiding principle (see PanelApi reference): the API reports *structure*, the
 * module decides *meaning*. It knows `const`/`let`/`var`, `output`, call vs
 * value, callees and their arguments — Strudel/JS vocabulary — never "clip",
 * "gate" or any module-specific term.
 *
 * Hard rules (see CodeRegionImpl):
 * - `source` slices the original text via acorn offsets — never re-generated.
 * - Reads never route through escodegen (`generate()` normalizes quotes,
 *   re-indents and drops comments — the destructive round-trip).
 * - Offsets are never cached across edits: every write re-resolves its region
 *   from the current text (a splice upstream shifts every offset downstream).
 */

/** How a top-level declaration is bound. The session model accepts only
 *  `const`; seeing `let`/`var` is its signal to surface a global error. The API
 *  reports what *is*; the consumer decides what *counts*. */
export type DeclKind = 'const' | 'let' | 'var';

/** What the initializer structurally is. `pattern` = a call (`stack(...)`,
 *  `note(...)`) imputed to Strudel. `value` = a literal or other non-call. */
export type InitKind = 'pattern' | 'value';

/**
 * A read-only view over one expression node, backed by the exact source text.
 * Compositional: `args()`/`items()` return spans whose `source` can be fed back
 * into `readExpr` to descend one level at a time. Offsets are relative to the
 * queried source, not to any document.
 */
export interface ExprQuery {
  /** True for a CallExpression (possibly chained, e.g. `stack(...).gain(...)`). */
  isCall(): boolean;
  /** True for an ArrayExpression (`[4, drums]`). */
  isArray(): boolean;
  /** Name of the root constructor call (`stack(a).gain(x)` → 'stack'), null
   *  when the expression is not a call. READ data, never a known list. */
  callee(): string | null;
  /** Flat arguments of the root call (`[]` when the expression is not a call). */
  args(): CallArg[];
  /** Elements of an array expression (`[]` when it is not an array). */
  items(): CallArg[];
}

/**
 * A top-level declaration read from the document. Pure structure: no notion of
 * "clip", "gate" or any consumer vocabulary.
 */
export interface Decl {
  /** Identifier of the declaration — its stable identity. */
  name: string;
  /** How it is bound (`const`/`let`/`var`). */
  declKind: DeclKind;
  /** Whether the initializer is a call (`pattern`) or not (`value`). */
  initKind: InitKind;
  /** Name of the constructor called, when `initKind === 'pattern'`. READ data,
   *  not a known list: a constructor invented tomorrow surfaces on its own. The
   *  consumer compares (`callee === 'stack'`) against ITS semantics. */
  callee?: string;
  /** Exact source of the initializer (sliced, never re-generated by escodegen). */
  source: string;
  /** Identifiers referenced by the initializer (e.g. members of a `stack`). */
  refs: string[];
  /** Span of the whole declaration in the document. */
  start: number;
  end: number;
  /** Span of the initializer — lets writes target it without `lastIndexOf`. */
  initStart: number;
  initEnd: number;
}

/** Where the live output lives, and in what form.
 *  `dollar`     = real Strudel `$:` syntax (closed).
 *  `expression` = any terminal expression (`arrange(...)`, `stack(...)`,
 *                 `cat(...)`…). The consumer reads the source and decides
 *                 ("starts with `arrange` → arrangement mode"). */
export type OutputRegion =
  | { kind: 'dollar'; start: number; end: number }
  | { kind: 'expression'; start: number; end: number }
  | { kind: 'none' };

/** An expression projected by the `$:` block, tagged structurally. "bare
 *  identifier = launched, otherwise step back" is the CONSUMER's policy; the
 *  API only reports whether it is a bare identifier. */
export interface DollarExpr {
  source: string;
  isIdentifier: boolean;
}

/** An argument of a call (`stack(s("bd"), bass)` → two CallArg). `isIdentifier`
 *  distinguishes the named member (steerable) from the inline (anonymous). */
export interface CallArg {
  source: string;        // 's("bd")'  or  'bass'
  isIdentifier: boolean; // false       |  true
  start: number;
  end: number;
}

/** A structural defect of the declaration graph (`[]` means the graph is OK). */
export interface GraphError {
  kind: 'dead-ref' | 'cycle' | 'duplicate' | 'syntax';
  /** Human-readable, precise message for the error banner. */
  detail: string;
}

export interface CodeRegion {
  // ── Reads (pure) ───────────────────────────────────────────────────────────

  /** All top-level declarations in source order, tagged by `declKind` and
   *  `initKind`. The consumer filters towards its own model. null on parse
   *  error (so a transient broken document keeps the current view). */
  list(code: string): Decl[] | null;

  /** Classify an arbitrary expression source. null if it is not a single
   *  expression. */
  readExpr(source: string): ExprQuery | null;

  /** Locate the live output region (the `$:` block or a terminal expression). */
  locateOutput(code: string): OutputRegion;

  /** Exact source of the output region (sliced via offsets), null when the
   *  document has no output. Consumers classify it with `readExpr` instead of
   *  slicing the document themselves. */
  outputSource(code: string): string | null;

  /** Expressions projected by the `$:` block, each tagged `isIdentifier`.
   *  Replaces the hand-rolled slice + split + regex on the consumer side. */
  dollarExprs(code: string): DollarExpr[];

  /** Arguments of the call that initializes `name` (null if it is not a call).
   *  Generic over any constructor — stack, cat, arrange — without naming them.
   *  FLAT: descends only one level; for an argument that is itself a call, call
   *  `callArgs` again on its span. */
  callArgs(code: string, name: string): CallArg[] | null;

  /** Validate the dependency graph: dead refs, cycles, duplicate names, syntax.
   *  Returns `[]` when the graph is valid. */
  validateGraph(decls: Decl[]): GraphError[];

  // ── Transforms (pure, code → code) ─────────────────────────────────────────

  /** Insert a declaration statement just before the output, on its own line
   *  (topological order preserved; newline handling owned here). */
  insertDecl(code: string, declText: string): string;

  /** Remove a declaration by name, with its trailing newlines. */
  removeDecl(code: string, name: string): string;

  /** Replace a declaration's initializer in place — splices only
   *  `initStart..initEnd`, leaving comments and spacing byte-identical. */
  setInit(code: string, name: string, source: string): string;

  /** Replace the output region (or add one if absent). Guarantees the document
   *  ends on an evaluable expression — the transpiler's hard rule. */
  setOutput(code: string, text: string): string;

  /** Remove the output region. */
  removeOutput(code: string): string;

  // ── Raw escape hatch (pure) — built-in only ────────────────────────────────

  /** Unchecked positional splice of `[start, end)` → `replacement`. */
  spliceSpan(code: string, start: number, end: number, replacement: string): string;
}
